Add image generator
pluemine/ocr-data-generation pull request #8
Opened 2024-09-03 10:30 UTC by pluemine

2024-09-03 10:33 UTC, boat1603 requested changes

2024-09-03 10:33 UTC, boat1603 commented on scripts/image_generator.py
> +def crop_text_from_image(img):
Please move some function to src

2024-09-03 10:59 UTC, pluemine commented on scripts/image_generator.py
> +def crop_text_from_image(img):
Done

2024-09-04 03:40 UTC, pluemine commented on scripts/image_generator.py
> +def crop_text_from_image(img):
Done

2024-09-04 04:08 UTC, merged